version: "2"
formatters:
  enable:
    - gofmt
    - goimports
linters:
  default: none
  enable:
    - bodyclose
    - gocritic
    - gosec
    - govet
    - nestif
    - nlreturn
    # - revive
    - rowserrcheck
    - staticcheck
  settings:
    gosec:
      excludes:
        - G104
        - G302
        - G304
        - G401
        - G501
