{{- if or (or (eq "all" .Values.global.deploymentType) (eq "internal" .Values.global.deploymentType) ) (not .Values.global.deploymentType)}}
{{- if not .Values.global.vaultSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-finalize
type: Opaque
stringData:
  config.yaml: |-
  {{- if .Values.global.backupArchive.storageType }}
    archive:
      type: {{ required "Archive storage type is not set" .Values.global.archive.storageType }}
    {{- if eq "s3" .Values.global.archive.storageType }}
      accessKey: {{ required "Accesskey required for archive" .Values.global.archive.s3AccessKey }}
      bucket: {{ required "S3 archive bucket not set" .Values.global.archive.s3Bucket }}
      {{- if and .Values.global.archive.s3CaFile .Values.global.tls.enabled }}
      caCert: {{ template "tlsPath" . }}/ca.crt
      {{ end }}
      chunksize: {{ default 15 .Values.global.archive.s3ChunkSize }}
      {{- if .Values.global.archive.s3Port }}
      port: {{ .Values.global.archive.s3Port }}
      {{- end }}
      readypath: {{ .Values.global.archive.s3ReadyPath }}
      secretKey: {{ required "Secretkey required for archive" .Values.global.archive.s3SecretKey }}
      url: {{ required "S3 archive URL missing" .Values.global.archive.s3Url }}
    {{- else }}
      location: /archive/
    {{- end }}
    backup:
      type: {{ .Values.global.backupArchive.storageType }}
    {{- if eq "s3" .Values.global.backupArchive.storageType }}
      accessKey: {{ required "Accesskey required for backup archive" .Values.global.backupArchive.s3AccessKey }}
      bucket: {{ required "S3 backup archive bucket not set" .Values.global.backupArchive.s3Bucket }}
      {{- if and .Values.global.backupArchive.s3CaFile .Values.global.tls.enabled }}
      caCert: {{ template "tlsPath" . }}/ca.crt
      {{ end }}
      chunksize: {{ default 15 .Values.global.backupArchive.s3ChunkSize }}
      {{- if .Values.global.backupArchive.s3Port }}
      port: {{ .Values.global.backupArchive.s3Port }}
      {{- end }}
      readypath: {{ .Values.global.backupArchive.s3ReadyPath }}
      secretKey: {{ required "Secretkey required for backup archive" .Values.global.backupArchive.s3SecretKey }}
      url: {{ required "S3 backup archive URL missing" .Values.global.backupArchive.s3Url }}
    {{- else }}
      location: /backup/
    {{- end }}
  {{- end }}
    broker:
    {{- if .Values.global.tls.enabled }}
      caCert: {{ template "tlsPath" . }}/ca.crt
      {{- if .Values.global.broker.verifyPeer }}
      clientCert: {{ template "tlsPath" . }}/tls.crt
      clientKey: {{ template "tlsPath" . }}/tls.key
      {{- end }}
    {{- end }}
      exchange: {{ default "sda" .Values.global.broker.exchange }}
      host: {{ required "A valid MQ host is required" .Values.global.broker.host }}
      port: {{ default (ternary 5671 5672 .Values.global.tls.enabled) .Values.global.broker.port }}
      prefetchCount: {{ default 1 .Values.global.broker.prefetchCount }}
      password: {{ required "MQ password is required" (include "mqPassFinalize" .) }}
      queue: {{ default "accession" .Values.global.broker.finalizeQueue }}
      routingKey: {{ default "completed" .Values.global.broker.finalizeRoutingKey }}
    {{- if ne "" ( default "" .Values.global.broker.serverName ) }}
      serverName: {{.Values.global.broker.serverName }}
    {{- end }}
      ssl: {{ .Values.global.tls.enabled }}
      user: {{ required "MQ user is required" (include "mqUserFinalize" .) }}
    {{- if .Values.global.tls.enabled }}
      verifyPeer: {{ .Values.global.broker.verifyPeer }}
    {{- end }}
      vhost: {{ include "brokerVhost" . }}
    db:
    {{- if .Values.global.tls.enabled }}
      caCert: {{ template "tlsPath" . }}/ca.crt
      clientCert: {{ template "tlsPath" . }}/tls.crt
      clientKey: {{ template "tlsPath" . }}/tls.key
    {{- end }}
      host: {{ .Values.global.db.host }}
      database: {{ .Values.global.db.name }}
      password: {{ required "MQ password is required" (include "dbPassFinalize" .) }}
      port: {{ .Values.global.db.port }}
      sslmode: {{ ternary .Values.global.db.sslMode "disable" .Values.global.tls.enabled }}
      user: {{ required "DB user is required" (include "dbUserFinalize" .) }}
    log:
      format: {{ .Values.global.log.format }}
      level: {{ .Values.global.log.level }}
    schema:
      type: {{ default "federated" .Values.global.schemaType }}
{{- end }}
{{- end }}
