{{- if eq "federated" .Values.global.schemaType }}
{{- if or (or (eq "all" .Values.global.deploymentType) (eq "internal" .Values.global.deploymentType) ) (not .Values.global.deploymentType) }}
{{- if not .Values.global.vaultSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-intercept
type: Opaque
stringData:
  config.yaml: |-
    broker:
    {{- if .Values.global.tls.enabled }}
      caCert: {{ template "tlsPath" . }}/ca.crt
      {{- if .Values.global.broker.verifyPeer }}
      clientCert: {{ template "tlsPath" . }}/tls.crt
      clientKey: {{ template "tlsPath" . }}/tls.key
      {{- end }}
    {{- end }}
      exchange: {{ default "sda" .Values.global.broker.exchange }}
      host: {{ required "A valid MQ host is required" .Values.global.broker.host }}
      port: {{ default (ternary 5671 5672 .Values.global.tls.enabled) .Values.global.broker.port }}
      prefetchCount: {{ default 1 .Values.global.broker.prefetchCount }}
      password: {{ required "MQ password is required" (include "mqPassInterceptor" .) }}
      queue: "from_cega"
    {{- if ne "" ( default "" .Values.global.broker.serverName ) }}
      serverName: {{.Values.global.broker.serverName }}
    {{- end }}
      ssl: {{ .Values.global.tls.enabled }}
      user: {{ required "MQ user is required" (include "mqUserInterceptor" .) }}
    {{- if .Values.global.tls.enabled }}
      verifyPeer: {{ .Values.global.broker.verifyPeer }}
    {{- end }}
      vhost: {{ include "brokerVhost" . }}
    log:
      format: {{ .Values.global.log.format }}
      level: {{ .Values.global.log.level }}
{{- end }}
{{- end }}
{{- end }}
