{{- if or (or (eq "all" .Values.global.deploymentType) (eq "internal" .Values.global.deploymentType) ) (not .Values.global.deploymentType)}}
{{- if not .Values.global.vaultSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-reencrypt
type: Opaque
stringData:
  config.yaml: |-
    c4gh:
    {{- with (first .Values.global.c4gh.privateKeys) }}
      filePath: {{ template "c4ghPath" $ }}/{{ .keyName }}
      passphrase: {{ required "a passphrase for the c4gh key is required" .passphrase }}
    {{-  end }}
    {{- if .Values.global.tls.enabled }}
    grpc:
      caCert: {{ template "tlsPath" . }}/ca.crt
      serverCert: {{ template "tlsPath" . }}/tls.crt
      serverKey: {{ template "tlsPath" . }}/tls.key
    {{- end }}
    log:
      format: {{ .Values.global.log.format }}
      level: {{ .Values.global.log.level }}
{{- end }}
{{- end }}
