apiVersion: v2
name: sda-svc
version: 2.0.7
appVersion: v2.0.18
kubeVersion: '>= 1.26.0'
description: Components for Sensitive Data Archive (SDA) installation
home: https://neic-sda.readthedocs.io
icon: https://neic.no/assets/images/logo.png
sources:
- https://github.com/neicnordic/sensitive-data-archive
