openapi: 3.0.3
info:
  title: SDA file download API
  version: "1.0"
paths:
  /file:
    get:
      description: Returns the requested file to the user
      parameters:
        - in: header
          description: "Public key used to re-encrypt the file (header) with. This should be supplied as the base64 encoding of the PEM (RFC 7468) encoding of the public key"
          name: public_key
          required: true
          schema:
            type: string
        - in: query
          name: dataset
          schema:
            type: string
          required: true
          description: Stable ID of the dataset
        - in: query
          name: fileId
          schema:
            type: string
          required: false
          description: Stable ID of the file to download. It is an error to supply both filePath and fileId
        - in: query
          name: filePath
          schema:
            type: string
          required: false
          description: File path of the file to download. It is an error to supply both filePath and fileId
        - in: query
          name: end
          description: 'End of requested data in the form of the 0-index of the first octet not included in the
                                 response. That is, data delivered will have octet indices in the closed-open set
                                 [start,end). Defaults to end of file if not set'
          required: false
          schema:
            minimum: 0
            type: integer
        - in: query
          name: start
          required: false
          schema:
            default: 0
            minimum: 0
            type: integer
      responses:
        "200":
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
          description: Successful operation
        "206":
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
          description: Successful partial file delivery
        "400":
          description: Bad request i.e start larger than end
        "401":
          description: Authentication failure
        "403":
          description: The user does not have access to the dataset
        "416":
          description: Unsatisfiable range i.e. end larger than file size
        "500":
          description: Internal application error
      security:
        - bearerAuth: []
  /file/{fileId}:
    get:
      description: Returns the requested file to the user
      parameters:
        - in: header
          description: "Public key used to re-encrypt the file header with"
          name: public_key
          required: true
          schema:
            type: string
        - in: path
          name: fileId
          schema:
            type: string
          required: true
          description: Stable ID of the file to download
        - in: header
          name: Range
          required: false
          schema:
            type: string
          description: 0-indexed byte range of the file that is to be delivered.
          example: "Range: bytes=20-200, 300-400"
      responses:
        "200":
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
          description: Successful operation
        "206":
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
          description: Successful partial file delivery
        "400":
          description: Bad request i.e start larger than end
        "401":
          description: Authentication failure
        "403":
          description: The user does not have access to the dataset
        "416":
          description: Unsatisfiable range i.e. end larger than file size
        "500":
          description: Internal application error
      security:
        - bearerAuth: []
  /info/datasets:
    get:
      description: Returns a list of the datasets the user has access to, an empty list is a valid response.
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              example: ["aa-dataset-123456-asdfgh", "bb-dataset-123456-asdfgh"]
              schema:
                type: array
        "401":
          description: Authentication failure
        "500":
          description: Internal application error
      security:
        - bearerAuth: []
  /info/datasets/{datasetId}:
    get:
      description: Returns an array with metadata about the dataset
      parameters:
        - in: header
          description: "Public key used to re-encrypt the file header with"
          name: public_key
          required: true
          schema:
            type: string
        - in: header
          description: "The JWT used to authenticate the user"
          name: token
          required: true
          schema:
            type: string
        - in: path
          name: datasetId
          schema:
            type: string
          required: true
          description: Stable ID of the dataset of interest
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DatasetInfo"
          description: Successful operation
        "401":
          description: Authentication failure
        "403":
          description: The user does not have access to the dataset
        "500":
          description: Internal application error
      security:
        - bearerAuth: []
  /info/datasets/{datasetId}/files:
    get:
      description: Returns an array with metadata about all files in a dataset
      parameters:
        - in: header
          description: "Public key used to re-encrypt the file header with"
          name: public_key
          required: true
          schema:
            type: string
        - in: header
          description: "The JWT used to authenticate the user"
          name: token
          required: true
          schema:
            type: string
        - in: path
          name: datasetId
          schema:
            type: string
          required: true
          description: Stable ID of the dataset of interest
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FileInfo"
          description: Successful operation
        "401":
          description: Authentication failure
        "403":
          description: The user does not have access to the dataset
        "500":
          description: Internal application error
      security:
        - bearerAuth: []
  /ready:
    get:
      description: Returns the status of the application, used by the Kubernets API to decide if traffic should be routed to the app
      responses:
        "200":
          description: The service is operational
        "503":
          description: Unhealthy service
components:
  schemas:
    DatasetInfo:
      type: object
      properties:
        date:
          type: string
          format: date-time
          example: "2025-02-14T14:51:26.639Z"
        files:
          type: integer
          format: int32
          example: 1234
        name:
          type: string
          example: aa-dataset-123456-asdfgh
        size:
          type: integer
          format: int64
          example: 6597069766656
    FileInfo:
      type: object
      properties:
        filePath:
          type: string
          example: "samples/controls/sample1.cram.c4gh"
        size:
          type: integer
          format: int64
          example: 56623104
        stableId:
          type: string
          example: aa-file-123456-asdfgh
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
